
name: diletta_sales_hq
publish_to: 'none'
version: 0.5.2
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hooks_riverpod: ^2.5.1
  go_router: ^14.8.1
  http: ^1.2.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  animations: ^2.0.11
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
