services:
  - type: web
    name: diletta-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PIPEDRIVE_API_TOKEN
        sync: false
      - key: CLIENT_DOMAIN
        value: diletta
      - key: ASSISTANT_MODEL
        value: gpt-4o-mini
      - key: PORT
        value: 10000
